# Generated by Django 4.2.2 on 2023-06-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField()),
                ('display', models.CharField(max_length=100, null=True)),
                ('display_size', models.CharField(null=True, verbose_name=100)),
                ('resolution', models.CharField(null=True, verbose_name=100)),
                ('os', models.CharField(null=True, verbose_name=100)),
                ('Weight', models.IntegerField(null=True)),
                ('batery', models.CharField(max_length=30, null=True)),
                ('colors', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green')], default='black')),
                ('Introduction', models.TextField(blank=True, null=True)),
                ('expert_check', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
