# Generated by Django 4.2.2 on 2023-06-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='Weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='batery',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='display_size',
            field=models.CharField(blank=True, null=True, verbose_name=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='os',
            field=models.CharField(blank=True, null=True, verbose_name=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='resolution',
            field=models.CharField(blank=True, null=True, verbose_name=100),
        ),
    ]
