# Generated by Django 4.2.2 on 2023-07-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='display',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='display_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=200, unique=True),
        ),
    ]
