# Generated by Django 4.2.2 on 2023-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_api', '0002_alter_mobile_weight_alter_mobile_batery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='display_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
