# Generated by Django 4.2.2 on 2023-07-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_api', '0002_mobile_display_mobile_display_size_mobile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='Weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
