# Generated by Django 4.2.2 on 2023-07-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_api', '0003_mobile_weight_mobile_os_mobile_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='Introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='batery',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mobile',
            name='expert_check',
            field=models.TextField(blank=True),
        ),
    ]
