# Generated by Django 4.2.2 on 2023-07-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_api', '0004_mobile_introduction_mobile_batery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
