# Generated by Django 4.2.2 on 2023-07-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_api', '0005_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='colors',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green')], default='black', max_length=100),
        ),
    ]
